nix.registry: lib.mkForce ... because
 … while calling the 'getAttr' builtin

                at /builtin/derivation.nix:19:19: (source not available)

              … while calling the 'derivationStrict' builtin

                at /builtin/derivation.nix:9:12: (source not available)

              (stack trace truncated; use '--show-trace' to show the full trace)

              error: The option `nix.registry.nixpkgs.to.path' has conflicting definition values:
              - In `/nix/store/gk27bip7ks4irrgkrcfkbnswmchbh0dy-source/nixos/modules/config/nix-flakes.nix': "/nix/store/11awh7g0yb00dazdc3q6wb62j88yyjir-source"
              - In `/nix/store/gk27bip7ks4irrgkrcfkbnswmchbh0dy-source/nixos/modules/misc/nixpkgs-flake.nix': "/nix/store/gk27bip7ks4irrgkrcfkbnswmchbh0dy-source"
              Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.